baseURL = 'https://sladjkf.github.io'
languageCode = 'en-us'
title = 'Nicholas Ruiyuan Wu'
theme = "etch"
publishDir="docs"
[menu]
  [[menu.main]]
    identifier = "resume"
    name = "resume"
    title = "resume"
    url = "/resume/"
    weight = 10
  [[menu.main]]
    identifier = "posts"
    name = "posts"
    title = "posts"
    url = "/posts/"
    weight = 10
  [[menu.main]]
    identifier = "research"
    name = "research"
    title = "research"
    url = "/research/"
    weight = 10


[markup.goldmark.renderer]
  # Allow HTML in Markdown
  unsafe = true

